In [1]:
import pandas as pd
import plotly.express as px

In [2]:
unemployment_path = "../dataset/Unemployment/"

unemployment_df = pd.read_csv(unemployment_path + "Unemployment_Rate_M_Total.txt").dropna()

In [3]:
unemployment_df

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%)
0,Andhra Pradesh,31-01-2016,M,17.91,20626291.0,62.67
1,Andhra Pradesh,29-02-2016,M,9.98,19334918.0,53.50
2,Andhra Pradesh,31-03-2016,M,10.72,19646970.0,54.73
3,Andhra Pradesh,30-04-2016,M,5.51,18929583.0,49.76
4,Andhra Pradesh,31-05-2016,M,6.29,21163390.0,56.02
...,...,...,...,...,...,...
2223,India,31-07-2022,M,6.83,397050067.0,38.94
2224,India,31-08-2022,M,8.28,394606374.0,39.24
2225,India,30-09-2022,M,6.43,404226503.0,39.32
2226,India,31-10-2022,M,7.77,396364024.0,39.04
2227,India,30-11-2022,M,8.00,401814180.0,39.60

In [4]:
unemployment_df_other = pd.read_csv(unemployment_path + "Unemployment_Rate_upto_11_2020.csv").dropna()

In [5]:
region_set=set()

In [6]:
for i in unemployment_df_other['Region']:
    region_set.add(i)

In [7]:
region_set

{'Andhra Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Meghalaya',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal'}

In [8]:
unemployment_df_other.columns

Index(['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Region.1', 'longitude', 'latitude'],
      dtype='object')

In [9]:
latitudes=[]
longitudes=[]
for state in region_set:
    latitude=unemployment_df_other.loc[unemployment_df_other['Region'] == state,'latitude' ].iloc[0]
    longitude=unemployment_df_other.loc[unemployment_df_other['Region'] == state,'longitude' ].iloc[0]
    latitudes.append(latitude)
    longitudes.append(longitude)

In [10]:
latitude_region_dict={}
longitude_region_dict={}
i=0
for state in region_set:
    latitude_region_dict[state]=latitudes[i]
    longitude_region_dict[state]=longitudes[i]
    i+=1

In [11]:
unemployment_df1=unemployment_df[unemployment_df['Region']!='India']

In [12]:
latitude_column=[]
longitude_column=[]

for state in unemployment_df1['Region']:
    latitude=latitude_region_dict[state]
    latitude_column.append(latitude)
    longitude=longitude_region_dict[state]
    longitude_column.append(longitude)

In [13]:
unemployment_df1['latitude']=latitude_column
unemployment_df1['longitude']=longitude_column

C:\Users\vishw\AppData\Local\Temp\ipykernel_8432\164170296.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment_df1['latitude']=latitude_column
C:\Users\vishw\AppData\Local\Temp\ipykernel_8432\164170296.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment_df1['longitude']=longitude_column

In [14]:
unemployment_df1

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),latitude,longitude
0,Andhra Pradesh,31-01-2016,M,17.91,20626291.0,62.67,79.740,15.9129
1,Andhra Pradesh,29-02-2016,M,9.98,19334918.0,53.50,79.740,15.9129
2,Andhra Pradesh,31-03-2016,M,10.72,19646970.0,54.73,79.740,15.9129
3,Andhra Pradesh,30-04-2016,M,5.51,18929583.0,49.76,79.740,15.9129
4,Andhra Pradesh,31-05-2016,M,6.29,21163390.0,56.02,79.740,15.9129
...,...,...,...,...,...,...,...,...
2140,West Bengal,31-07-2022,M,6.26,35776902.0,44.36,87.855,22.9868
2141,West Bengal,31-08-2022,M,7.39,35811552.0,44.85,87.855,22.9868
2142,West Bengal,30-09-2022,M,3.28,36835286.0,44.09,87.855,22.9868
2143,West Bengal,31-10-2022,M,4.84,35391928.0,42.98,87.855,22.9868
2144,West Bengal,30-11-2022,M,5.43,36095769.0,44.02,87.855,22.9868

In [15]:
def get_animation(unemployment_df_other):
    unemployment_df_other1=unemployment_df_other.copy()
    unemployment_df_other1[' Date'] = pd.to_datetime(unemployment_df_other1[' Date'],dayfirst=True)

    unemployment_df_other1['Year'] =  unemployment_df_other1[' Date'].dt.year

    fig = px.scatter_geo(unemployment_df_other1,'longitude', 'latitude', color="Region",
                     hover_name="Region", size=" Estimated Unemployment Rate (%)",
                     animation_frame="Year",scope='asia',template='plotly',title='Unemployment Rate in India from 2016 to 2022')
    
    frames = []
    for s, fr in enumerate(fig.frames):
        # set main traces to appropriate traces within plotly frame
        fig.update(data=fr.data)
        # move slider to correct place
        fig.layout.sliders[0].update(active=s)
        # generate image of current state
        frames.append(PIL.Image.fromopen(io.BytesIO(fig.to_image(format="png"))))

    # create animated GIF
    frames[0].save(
            "test.gif",
            save_all=True,
            append_images=frames[1:],
            optimize=True,
            duration=500,
            loop=0,
        )
    fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 2000

    fig.update_geos(lataxis_range=[5,35], lonaxis_range=[65, 100],oceancolor="#6dd5ed", showocean=True)
    fig.show()

In [16]:
get_animation(unemployment_df1)

NameError: name 'PIL' is not defined

In [27]:
!pip install kaleido

Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-macosx_11_0_arm64.whl (85.8 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 85.8 MB 313 kB/s  eta 0:00:01
Installing collected packages: kaleido
Successfully installed kaleido-0.2.1

In [17]:
import PIL
import io

In [18]:
frames = []
for s, fr in enumerate(fig.frames):
    # set main traces to appropriate traces within plotly frame
    fig.update(data=fr.data)
    # move slider to correct place
    fig.layout.sliders[0].update(active=s)
    # generate image of current state
    frames.append(PIL.Image.open(io.BytesIO(fig.to_image(format="png"))))
    
# create animated GIF
frames[0].save(
        "test.gif",
        save_all=True,
        append_images=frames[1:],
        optimize=True,
        duration=500,
        loop=0,
    )

AttributeError: 'NoneType' object has no attribute 'frames'